/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ventanas;

import javax.swing.WindowConstants;

/**
 *
 * @author USUARIO
 */
public class Proveedor extends javax.swing.JFrame {

    /** Creates new form Proveedor */
    String usuario;
    
    public Proveedor() {
        initComponents();
        setSize(1340, 698);
        setResizable(false);
        usuario = Login.user;
        setTitle("Usuario registrado - Sesión de " + usuario);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCliente = new javax.swing.JTable();
        jButtonAgregar = new javax.swing.JButton();
        jButtonModificar = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();
        jLabelBuscar = new javax.swing.JLabel();
        jButtonSalir = new javax.swing.JButton();
        jTextFieldBuscar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nro articulo", "Suprubro", "Rubro", "Subrubro", "Nombre ", "Marca", "Precio final", "Stock", "Estado", "Código barras"
            }
        ));
        jTableCliente.setGridColor(new java.awt.Color(240, 240, 240));
        jTableCliente.setSelectionForeground(new java.awt.Color(255, 0, 51));
        jTableCliente.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTableCliente);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 1290, 430));

        jButtonAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add_insert_plus_1588.png"))); // NOI18N
        jButtonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, 100, 100));

        jButtonModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/editar.png"))); // NOI18N
        jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 550, 100, 100));

        jButtonEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete_delete_exit_1577.png"))); // NOI18N
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 550, 100, 100));

        jLabelBuscar.setFont(new java.awt.Font("Perkeo", 1, 18)); // NOI18N
        jLabelBuscar.setText("Busqueda po nro de Articulo");
        getContentPane().add(jLabelBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 550, 210, 24));

        jButtonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit_closethesession_close_6317.png"))); // NOI18N
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 540, 100, 100));

        jTextFieldBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldBuscarMouseClicked(evt);
            }
        });
        jTextFieldBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBuscarActionPerformed(evt);
            }
        });
        jTextFieldBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldBuscarKeyPressed(evt);
            }
        });
        getContentPane().add(jTextFieldBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 600, 200, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarActionPerformed
        try {
            // Insertar articulo nuevo
            idarticulo = "0";
            bandera = "1";
            ArticuloABM Art = new ArticuloABM();
            Art.setVisible(true);
            this.setVisible(false);
        } catch (DocumentException ex) {
            Logger.getLogger(Articulo.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButtonAgregarActionPerformed

    private void jButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarActionPerformed
        // TODO add your handling code here:
        filaseleccionada = jTableArticulo.getSelectedRow();
        if (filaseleccionada == -1) {
            JOptionPane.showMessageDialog(null, "No ha seleccionado articulo.");
        } else {
            try {
                //JOptionPane.showMessageDialog(null, "Selecciono articulo.");
                idarticulo = (String) jTableArticulo.getValueAt(filaseleccionada, 0);
                bandera = "2";
                ArticuloABM Art = new ArticuloABM();
                Art.setVisible(true);
                this.setVisible(false);
            } catch (DocumentException ex) {
                Logger.getLogger(Articulo.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButtonModificarActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        // TODO add your handling code here:
        //Seleccionar fila encontrando id de articulo
        filaseleccionada = jTableArticulo.getSelectedRow();
        if (filaseleccionada == -1) {
            JOptionPane.showMessageDialog(null, "No ha seleccionado articulo.");
        } else {
            try {
                //JOptionPane.showMessageDialog(null, "Selecciono articulo.");
                idarticulo = (String) jTableArticulo.getValueAt(filaseleccionada, 0);
                bandera = "3";
                ArticuloABM Art = new ArticuloABM();
                Art.setVisible(true);
                this.setVisible(false);
            } catch (DocumentException ex) {
                Logger.getLogger(Articulo.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        //Volver de donde vino clase Administrador
        Administrador Adm = new Administrador();
        Adm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jTextFieldBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldBuscarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBuscarMouseClicked

    private void jTextFieldBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBuscarActionPerformed

    private void jTextFieldBuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBuscarKeyPressed
        // TODO add your handling code here:
        String[] titulos = {"Nro cliente", "Nombre cliente", "CUIL", "Dirección", "Teléfono fijo", "Celular", "Correo"};
        String[] registros = new String[500];
        String sql;
        sql = "select * from cliente as cl\n"
        + "where cli_idcliente like '%" + jTextFieldBuscar.getText() + "%'"
        + "or cli_nomcliente like '%" + jTextFieldBuscar.getText() + "%'"
        + "or cli_cuil like '%" + jTextFieldBuscar.getText() + "%'"
        + "or cli_direccion like '%" + jTextFieldBuscar.getText() + "%'"
        + "or cli_correo like '%" + jTextFieldBuscar.getText() + "%'"
        + "or cli_celular like '%" + jTextFieldBuscar.getText() + "%'"
        + "or cli_telefono like '%" + jTextFieldBuscar.getText() + "%'";
        System.out.print(sql);
        model = new DefaultTableModel(null, titulos);
        try {
            Connection cn;
            cn = Conexion.conectar();
            PreparedStatement pst;
            pst = cn.prepareStatement(sql);
            System.out.println(sql);
            ResultSet rs = pst.executeQuery();
            while (rs.next()) {
                registros[0] = rs.getString("art_idarticulo");
                registros[1] = rs.getString("suprub_nombre");
                registros[2] = rs.getString("rub_nombre");
                registros[3] = rs.getString("subru_nombre");
                registros[4] = rs.getString("art_nombre");
                registros[5] = rs.getString("mar_nombremarca");
                registros[6] = rs.getString("art_preciofinal");
                registros[7] = rs.getString("art_stock");
                model.addRow(registros);
            }
            jTableCliente.setModel(model);
        } catch (SQLException ex) {
            Logger.getLogger(Cliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTextFieldBuscarKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Proveedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregar;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabelBuscar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableCliente;
    private javax.swing.JTextField jTextFieldBuscar;
    // End of variables declaration//GEN-END:variables

}
