/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import javax.swing.WindowConstants;

/**
 *
 * @author USUARIO
 */
public class PuntoVenta extends javax.swing.JFrame {

    /**
     * Creates new form PuntoVenta
     */
    
    String usuario;
    
    public PuntoVenta() {
        initComponents();
        setSize(1340, 698);
        setResizable(false);
        usuario = Login.user;
        setTitle("Usuario registrado - Sesión de " + usuario);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        jButtonAgregar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jLabelBuscar = new javax.swing.JLabel();
        jTextFieldBuscar = new javax.swing.JTextField();
        jButtonSalir = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jButtonGuardar = new javax.swing.JButton();
        jButtonBuscar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButtonAgregar2 = new javax.swing.JButton();
        jButtonEliminar1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("FECHA");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 110, 30));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 220, 40));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "CODIGO", "DESCRIPCION", "CANTIDAD", "PRECIO UNITARIO", "TOTAL"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 770, 260));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 160, 40));

        jLabel3.setText("CODIGO");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 110, 30));

        jButton3.setText("IMPRIMIR TICKET");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 480, 120, 100));

        jLabel4.setText("ELIMINA ARTICULO DETALLE");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 280, 140, 30));
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 70, 230, 50));

        jLabel2.setText("SUB-TOTAL");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 450, 60, 30));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 440, 150, 40));

        jLabel5.setText("DESCUENTOS");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 520, 70, 30));
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 510, 170, 40));

        jLabel6.setText("TOTAL");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 550, 60, 30));

        jLabel7.setText("IMPUESTOS");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 500, 60, 30));
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 540, 150, 40));
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 490, 150, 40));

        jLabel8.setText("ARTICULOS");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, 70, 30));
        getContentPane().add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 450, 170, 40));

        jButton9.setText("REGISTAR");
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, 120, 90));

        jButtonAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add_insert_plus_1588.png"))); // NOI18N
        jButtonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 20, 100, 100));

        jButtonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete_delete_exit_1577.png"))); // NOI18N
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 450, 100, 100));

        jLabelBuscar.setFont(new java.awt.Font("Perkeo", 1, 18)); // NOI18N
        jLabelBuscar.setText("Busqueda por nro de Articulo");
        getContentPane().add(jLabelBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 330, 210, 24));

        jTextFieldBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldBuscarMouseClicked(evt);
            }
        });
        jTextFieldBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldBuscarKeyPressed(evt);
            }
        });
        getContentPane().add(jTextFieldBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 360, 240, 40));

        jButtonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit_closethesession_close_6317.png"))); // NOI18N
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 480, 100, 100));

        jLabel10.setText("DETALLE FACTURA");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, 110, 30));

        jButtonGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add_insert_plus_1588.png"))); // NOI18N
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 450, 100, 100));

        jButtonBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buscar2.png"))); // NOI18N
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 20, 100, 100));

        jLabel9.setText("CLIENTE");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 40, 50, 30));

        jLabel11.setText("CANCELAR");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 550, 80, 30));

        jButtonAgregar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add_insert_plus_1588.png"))); // NOI18N
        jButtonAgregar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregar2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAgregar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 180, 100, 100));

        jButtonEliminar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete_delete_exit_1577.png"))); // NOI18N
        jButtonEliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminar1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEliminar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 180, 100, 100));

        jLabel13.setText("GUARDAR");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 550, 80, 30));

        jLabel12.setText("BUSQUEDA");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 120, 80, 30));

        jLabel14.setText("ALTA ARTICULO");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 280, 80, 30));

        jLabel15.setText("ALTA CLIENTE");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 120, 80, 30));
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButtonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarActionPerformed
        try {
            // Insertar articulo nuevo
            idarticulo = "0";
            bandera = "1";
            ArticuloABM Art = new ArticuloABM();
            Art.setVisible(true);
            this.setVisible(false);
        } catch (DocumentException ex) {
            Logger.getLogger(Articulo.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButtonAgregarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
        //Seleccionar fila encontrando id de articulo
        filaseleccionada = jTableArticulo.getSelectedRow();
        if (filaseleccionada == -1) {
            JOptionPane.showMessageDialog(null, "No ha seleccionado articulo.");
        } else {
            try {
                //JOptionPane.showMessageDialog(null, "Selecciono articulo.");
                idarticulo = (String) jTableArticulo.getValueAt(filaseleccionada, 0);
                bandera = "3";
                ArticuloABM Art = new ArticuloABM();
                Art.setVisible(true);
                this.setVisible(false);
            } catch (DocumentException ex) {
                Logger.getLogger(Articulo.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jTextFieldBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldBuscarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBuscarMouseClicked

    private void jTextFieldBuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBuscarKeyPressed
        // TODO add your handling code here:
        String[] titulos = {"Nro articulo","Suprubro","Rubro","Subrubro","Nombre","Marca","Precio final","Stock","Estado","Código barras"};
        String[] registros = new String [300];
        String sql;
        /*sql = "select * from articulo where art_idarticulo like '%" + jTextFieldBuscar.getText() + "%'"
        + "or art_suprubro like '%" + jTextFieldBuscar.getText() + "%'"
        + "or art_rubro like '%" + jTextFieldBuscar.getText() + "%'"
        + "or art_subrubro like '%" + jTextFieldBuscar.getText() + "%'"
        + "or art_nombre like '%" + jTextFieldBuscar.getText() + "%'"
        + "or art_idmarca like '%" + jTextFieldBuscar.getText() + "%'";*/
        sql = "select * from articulo where art_nombre like"+'"'+ jTextFieldBuscar.getText()+'"'+"%'";
        model = new DefaultTableModel(null, titulos);
        try {
            Connection cn;
            cn = Conexion.conectar();
            PreparedStatement pst;
            pst = cn.prepareStatement(sql);
            System.out.println(sql);
            ResultSet rs = pst.executeQuery();
            while (rs.next()){
                //registros[0] = rs.getString("art_idarticulo");
                //registros[1] = rs.getString("art_suprubro");
                //registros[2] = rs.getString("art_rubro");
                //registros[3] = rs.getString("art_subrubro");
                registros[4] = rs.getString("art_nombre");
                //registros[5] = rs.getString("art_marca");
                model.addRow(registros);
            }
            jTableArticulo.setModel(model);
        } catch (SQLException ex) {
            Logger.getLogger(Articulo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTextFieldBuscarKeyPressed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        //Volver de donde vino clase Administrador
        Administrador Adm = new Administrador();
        Adm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed

        //Busqueda filtrada
        String[] titulos = {"Nro articulo", "Suprubro", "Rubro", "Subrubro", "Nombre", "Marca", "Precio final", "Stock"};
        String[] registros = new String[500];

        if (jComboBoxSupRubro.getSelectedItem() == "Libreria") {
            filtro1 = "Libreria";
        }
        if (jComboBoxSupRubro.getSelectedItem() == "Artistica") {
            filtro1 = "Artistica";
            System.out.print(filtro1);
        }
        if (jComboBoxSupRubro.getSelectedItem() == "Computación") {
            filtro1 = "Computación";
        }
        if (jComboBoxSupRubro.getSelectedItem() == "Regalería") {
            filtro1 = "Regalería";
        }
        if (jComboBoxSupRubro.getSelectedItem() == "Tarjetería") {
            filtro1 = "Tarjetería";
        }
        if (jComboBoxSupRubro.getSelectedItem() == "Impresiones/Fotocopias") {
            filtro1 = "Impresiones/Fotocopias";
        }
        if (jComboBoxSupRubro.getSelectedItem() == "Cotillón") {
            filtro1 = "Cotillón";
        }
        if (jComboBoxSupRubro.getSelectedItem() == "Mercería") {
            filtro1 = "Mercería";
        }
        if (jComboBoxRubro.getSelectedItem() == "Accesorios de escritorio") {
            filtro2 = "Accesorios de escritorio";
        }
        if (jComboBoxRubro.getSelectedItem() == "Adhesivos") {
            filtro2 = "Adhesivos";
        }
        if (jComboBoxRubro.getSelectedItem() == "Artículos Patrios") {
            filtro2 = "Artículos Patrios";
        }
        if (jComboBoxRubro.getSelectedItem() == "Calculadoras") {
            filtro2 = "Calculadoras";
        }
        if (jComboBoxRubro.getSelectedItem() == "Cartucheras") {
            filtro2 = "Cartucheras";
        }
        if (jComboBoxRubro.getSelectedItem() == "Carpetas y archivos") {
            filtro2 = "Carpetas y archivos";
        }
        if (jComboBoxRubro.getSelectedItem() == "Marroquineria") {
            filtro2 = "Marroquineria";
        }
        if (jComboBoxRubro.getSelectedItem() == "Pizarras y accesorios") {
            filtro2 = "Pizarras y accesorios";
        }
        if (jComboBoxRubro.getSelectedItem() == "Papelería") {
            filtro2 = "Papelería";
        }
        if (jComboBoxRubro.getSelectedItem() == "Folios") {
            filtro2 = "Folios";
        }
        if (jComboBoxRubro.getSelectedItem() == "Escritura") {
            filtro2 = "Escritura";
        }
        if (jComboBoxRubro.getSelectedItem() == "Encuadernación") {
            filtro2 = "Encuadernación";
        }
        if (jComboBoxRubro.getSelectedItem() == "Embalaje") {
            filtro2 = "Embalaje";
        }
        if (jComboBoxRubro.getSelectedItem() == "Geometría y dibujo") {
            filtro2 = "Geometría y dibujo";
        }
        if (jComboBoxRubro.getSelectedItem() == "Didáctico y manualidades") {
            filtro2 = "Didáctico y manualidades";
        }
        if (jComboBoxRubro.getSelectedItem() == "Cuadernos") {
            filtro2 = "Cuadernos";
        }
        if (jComboBoxRubro.getSelectedItem() == "Libros") {
            filtro2 = "Libros";
        }
        if (jComboBoxRubro.getSelectedItem() == "Repuestos") {
            filtro2 = "Repuestos";
        }
        if (jComboBoxRubro.getSelectedItem() == "Tijeras") {
            filtro2 = "Tijeras";
        }
        if (jComboBoxRubro.getSelectedItem() == "Resmas") {
            filtro2 = "Resmas";
        }
        if (jComboBoxRubro.getSelectedItem() == "Accesorios") {
            filtro2 = "Accesorios";
        }
        if (jComboBoxRubro.getSelectedItem() == "Pinturas") {
            filtro2 = "Pinturas";
        }
        if (jComboBoxRubro.getSelectedItem() == "Herramientas") {
            filtro2 = "Herramientas";
        }
        if (jComboBoxRubro.getSelectedItem() == "Pinceles") {
            filtro2 = "Pinceles";
        }
        if (jComboBoxRubro.getSelectedItem() == "Técnicas Secas") {
            filtro2 = "Técnicas Secas";
        }
        if (jComboBoxRubro.getSelectedItem() == "Accesorios Madera") {
            filtro2 = "Accesorios Madera";
        }
        if (jComboBoxRubro.getSelectedItem() == "Masas Manualidades") {
            filtro2 = "Masas Manualidades";
        }
        if (jComboBoxRubro.getSelectedItem() == "Decoopages") {
            filtro2 = "Decoopages";
        }
        if (jComboBoxRubro.getSelectedItem() == "Accesorios y Cables") {
            filtro2 = "Accesorios y Cables";
        }
        if (jComboBoxRubro.getSelectedItem() == "Accesorios Celulares") {
            filtro2 = "Accesorios Celulares";
        }

        if (jComboBoxSubRubro.getSelectedItem() == "Carpetas escolares") {
            filtro3 = "Carpetas escolares";
        }
        if (jComboBoxSubRubro.getSelectedItem() == "Biblioratos") {
            filtro3 = "Biblioratos";
        }
        if (jComboBoxSubRubro.getSelectedItem() == "Carpetas Universitarias") {
            filtro3 = "Carpetas Universitarias";
        }
        if (jComboBoxSubRubro.getSelectedItem() == "Carpetas Dibujo") {
            filtro3 = "Carpetas Dibujo";
        }
        if (jComboBoxSubRubro.getSelectedItem() == "Tapa dura") {
            filtro3 = "Tapa dura";
        }
        if (jComboBoxSubRubro.getSelectedItem() == "Tapa flexible") {
            filtro3 = "Tapa flexible";
        }
        if (jComboBoxSubRubro.getSelectedItem() == "Espiralado") {
            filtro3 = "Espiralado";
        }
        if (jComboBoxSubRubro.getSelectedItem() == "Block") {
            filtro3 = "Block";
        }
        if (jComboBoxSubRubro.getSelectedItem() == "Carpetas Oficina") {
            filtro3 = "Carpetas Oficina";
        }
        if (jComboBoxSubRubro.getSelectedItem() == "Repuestos Escolares") {
            filtro3 = "Repuestos Escolares";
        }
        if (jComboBoxSubRubro.getSelectedItem() == "Repuestos Universitarios") {
            filtro3 = "Repuestos Universitarios";
        }
        if (jComboBoxSubRubro.getSelectedItem() == "Repuestos Dibujo") {
            filtro3 = "Repuestos Dibujo";
        }

        if (jComboBoxMarca.getSelectedItem() == "Faber Castell") {
            filtro4 = "Faber Castell";
        }
        if (jComboBoxMarca.getSelectedItem() == "Rivadavia") {
            filtro4 = "Rivadavia";
        }
        if (jComboBoxMarca.getSelectedItem() == "Rexon") {
            filtro4 = "Rexon";
        }
        if (jComboBoxMarca.getSelectedItem() == "Generica") {
            filtro4 = "Generica";
        }
        if (jComboBoxMarca.getSelectedItem() == "Pizzini") {
            filtro4 = "Pizzini";
        }
        if (jComboBoxMarca.getSelectedItem() == "Laprida") {
            filtro4 = "Laprida";
        }
        if (jComboBoxMarca.getSelectedItem() == "Exito") {
            filtro4 = "Exito";
        }
        if (jComboBoxMarca.getSelectedItem() == "Señorita") {
            filtro4 = "Señorita";
        }
        if (jComboBoxMarca.getSelectedItem() == "Boligoma") {
            filtro4 = "Boligoma";
        }
        if (jComboBoxMarca.getSelectedItem() == "Filgo") {
            filtro4 = "Filgo";
        }
        if (jComboBoxMarca.getSelectedItem() == "Pelikan") {
            filtro4 = "Pelikan";
        }
        if (jComboBoxMarca.getSelectedItem() == "Faber") {
            filtro4 = "Faber";
        }
        if (jComboBoxMarca.getSelectedItem() == "BIC") {
            filtro4 = "BIC";
        }
        if (jComboBoxMarca.getSelectedItem() == "Micro") {
            filtro4 = "Micro";
        }
        if (jComboBoxMarca.getSelectedItem() == "Paper Mate") {
            filtro4 = "Paper Mate";
        }
        if (jComboBoxMarca.getSelectedItem() == "Maped") {
            filtro4 = "Maped";
        }
        if (jComboBoxMarca.getSelectedItem() == "Tintoretto") {
            filtro4 = "Tintoretto";
        }
        if (jComboBoxMarca.getSelectedItem() == "Alba") {
            filtro4 = "Alba";
        }
        if (jComboBoxMarca.getSelectedItem() == "Staedler") {
            filtro4 = "Staedler";
        }
        if (jComboBoxMarca.getSelectedItem() == "Trabi") {
            filtro4 = "Trabi";
        }
        if (jComboBoxMarca.getSelectedItem() == "Playcolor") {
            filtro4 = "Playcolor";
        }
        if (jComboBoxMarca.getSelectedItem() == "Pagoda") {
            filtro4 = "Pagoda";
        }
        if (jComboBoxMarca.getSelectedItem() == "Ezco") {
            filtro4 = "Ezco";
        }
        if (jComboBoxMarca.getSelectedItem() == "Pampa") {
            filtro4 = "Pampa";
        }
        if (jComboBoxMarca.getSelectedItem() == "Boreal") {
            filtro4 = "Boreal";
        }
        if (jComboBoxMarca.getSelectedItem() == "América") {
            filtro4 = "América";
        }
        if (jComboBoxMarca.getSelectedItem() == "Gloria") {
            filtro4 = "Gloria";
        }
        if (jComboBoxMarca.getSelectedItem() == "Triunfante") {
            filtro4 = "Triunfante";
        }
        if (jComboBoxMarca.getSelectedItem() == "Arte") {
            filtro4 = "Arte";
        }
        if (jComboBoxMarca.getSelectedItem() == "Proarte") {
            filtro4 = "Proarte";
        }
        valor1 = (String) jComboBoxSupRubro.getSelectedItem();
        //System.out.print(valor1);
        valor2 = (String) jComboBoxRubro.getSelectedItem();
        //System.out.print(valor2);
        valor3 = (String) jComboBoxSubRubro.getSelectedItem();
        //System.out.print(valor3);
        valor4 = (String) jComboBoxMarca.getSelectedItem();
        //System.out.print(valor4);
        String sql;
        sql = "select * from articulo as ar\n"
        + "LEFT JOIN superrubro as sru ON ar.art_idsuprubro=sru.suprub_idsuprubro\n"
        + "LEFT JOIN rubro as ru       ON ar.art_idrubro=ru.rub_idrubro\n"
        + "LEFT JOIN subrubro as sr    ON ar.art_idsubrubro=sr.subru_idsubrubro\n"
        + "LEFT JOIN marca as ma       ON ar.art_idmarca=ma.mar_idmarca\n"
        + "where" +filtro1+ "like '%" + valor1 + "%'"
        + "or" +filtro2+ "like '%" + valor2 + "%'"
        + "or" +filtro3+ "like '%" + valor3 + "%'"
        + "or" +filtro4+ "like '%" + valor4 + "%'";
        System.out.print(sql);
        model = new DefaultTableModel(null, titulos);
        try {
            Connection cn;
            cn = Conexion.conectar();
            PreparedStatement pst;
            pst = cn.prepareStatement(sql);
            System.out.println(sql);
            ResultSet rs = pst.executeQuery();
            while (rs.next()) {
                registros[0] = rs.getString("art_idarticulo");
                registros[1] = rs.getString("suprub_nombre");
                registros[2] = rs.getString("rub_nombre");
                registros[3] = rs.getString("subru_nombre");
                registros[4] = rs.getString("art_nombre");
                registros[5] = rs.getString("mar_nombremarca");
                registros[6] = rs.getString("art_preciofinal");
                registros[7] = rs.getString("art_stock");
                model.addRow(registros);
            }
            jTableArticulo.setModel(model);
        } catch (SQLException ex) {
            Logger.getLogger(Articulo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jButtonAgregar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAgregar2ActionPerformed

    private void jButtonEliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEliminar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PuntoVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PuntoVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PuntoVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PuntoVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PuntoVenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonAgregar;
    private javax.swing.JButton jButtonAgregar2;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEliminar1;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelBuscar;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextFieldBuscar;
    // End of variables declaration//GEN-END:variables
}
